[providers.go]
version = "1.23.0"

[phases.setup]
cmds = ["go mod download"]

[phases.build]
cmds = [
    "go build -o main .",
    "chmod +x main",
    "ls -la main"
]

[start]
cmd = "chmod +x start.sh && ./start.sh"

[variables]
CGO_ENABLED = "0"
GOOS = "linux"
