[build]
builder = "nixpacks"

[deploy]
startCommand = "./main"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[variables]
PORT = "8000"
GO_VERSION = "1.23.0"
